### ISSUE TITLE
Panda Moveit Position Controller

### ISSUE THREAD

**Issue by 6itf1ip** [AndrejOrsula/panda_ign#36]
I spawn the panda robotic arm in gazebo ignition, and then I use ign_control, position interface, to make the robot not to fall. I have used your panda.urdf and panda.srdf file. I have make changes in the urdf file as it was written for effort interface. Using your move group launch file, to make the robot works with moveit2, but I am getting error. Even if I am creating my own moveit setup it is still not working or have a joint violation which makes the robot not to move in a certain position

**Comment by AndrejOrsula** [comment]
Hello @6itf1ip,

Thanks for opening this issue.
First of all, have you managed to use this package as is without modifications? The included launch script already uses an effort-based interface. If you want to use position, simply change it to "position" and check if it works. However, the position interface will prevent the robot from interacting with the rest of the physics scene.

https://github.com/AndrejOrsula/panda_ign_moveit2/blob/8e5c6fd5d0d39ce2ad1d14968f86104f4ae0b9cb/panda_moveit_config/launch/ex_ign_control.launch.py#L56

**Comment by peakyquest** [comment]
Thanks for replying so you are suggesting me to work on effort interface instead of position ?

**Comment by AndrejOrsula** [comment]
Effort is better if you want your robot to interact with other objects.
If you don't have any interactions and your focus is elsewhere (e.g. vision), then the position is totally fine.

**Comment by peakyquest** [comment]
ok thanks for a quick reply, I am using urdf instead of xacro file, will it make any difference, and how to use the panda.urdf in the `move.group.launch.py` and `ex_ign_control.launch.py`?

**Comment by AndrejOrsula** [comment]
You will have to add the corresponding plugins on your own if you don't use the provided xacro. I recommend you to just update the xacro as you need.

**Comment by peakyquest** [comment]
In `ex_ign_control.launch.py`

```
        # ros_ign_gazebo_create
        Node(
            package="ros_ign_gazebo",
            executable="create",
            output="log",
            arguments=["-file", model, "--ros-args", "--log-level", log_level],
            parameters=[{"use_sim_time": use_sim_time}],
        ),
```

we are calling the sdf model of panda or xacro file of panda ?

**Comment by AndrejOrsula** [comment]
Xacro is called here:

https://github.com/AndrejOrsula/panda_ign_moveit2/blob/8e5c6fd5d0d39ce2ad1d14968f86104f4ae0b9cb/panda_moveit_config/launch/move_group.launch.py#L52-L101

**Comment by peakyquest** [comment]
Thanks, with the help of your reop I was able to move the robotic arm but there is one issue which I am facing is that only one finger gripper is moving.  I set the following config for my ign ros2 control

```
# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    panda_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    panda_gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

panda_arm_controller:
  ros__parameters:
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

panda_gripper_controller:
  ros__parameters:
    joints:
      - panda_finger_joint1
      - panda_finger_joint2
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

```

and my moveit_controllers config as: 


```
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - panda_arm_controller
    - panda_gripper_controller

  panda_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7

  panda_gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    joints:
      - panda_finger_joint1
      - panda_finger_joint2


```
